### ISSUE TITLE
Backend - Base 뼈대 작업

### ISSUE THREAD

**Issue by jtjun** [osamhack2020/WEB_SAMarket_SAMarket#2]
CI, 프로젝트 뼈대 구성 등 Base 작업

**Comment by woolimcho** [comment]
https://github.com/osamhack2020/WEB_SAMarket_SAMarket/commit/04736c5b7d3e3eedadb35f64bafaa169d01c3e62
https://github.com/osamhack2020/WEB_SAMarket_SAMarket/commit/91f577bc3231292e43afb631a363298d75f587c2
