### ISSUE TITLE
Backend: 채팅방 구현

### ISSUE THREAD

**Issue by woolimcho** [osamhack2020/WEB_SAMarket_SAMarket#23]
### WebSocket
- [x] Gin + 웹소켓 테스트
- [x] 웹소켓을 유저 UUID에 대응
- [x] 메시지 전송 함수 및 테스트 API 추가

### DB
- [x] 채팅 모델 구현

### API
- [x] 채팅방 생성, 채팅 전송 API 구현
<del>Redis 연동</del>

**Comment by jkl5616** [comment]
https://github.com/osamhack2020/WEB_SAMarket_SAMarket/commit/8a3860cf374346b9468bce8d9e1f539859ecb1f4
